name: Maven Lint and Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Checkstyle Lint
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven

      - name: Execute Checkstyle Lint
        run: mvn --quiet -B clean checkstyle:check
  test:
    name: Maven Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven

      - name: Execute Maven Test
        run: mvn --quiet -B clean test

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2

      - name: Commit And Push JaCoCo Badge
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Autogenerated JaCoCo Badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/